### ISSUE TITLE
Hello, can you send tthese files ？

### ISSUE THREAD

**Issue by clancylea** [jmduarte/pynq_hls4ml#2]
Hello, can you send tthese files ？
 hls4ml_demo.bit
hls4ml_demo.hwh
X_test.npy
y_hls.npy
Thank you，lol！！！

**Comment by jmduarte** [comment]
Hi @clancylea, these files are meant to be generated by the first notebook. Does it not work for you?

**Comment by wilfredkisku** [comment]
Could you please help me with this issue that comes up when I am using Vivado HLS 2018.2, 2019.2 and 2020.1 during synthesis. This happens during the build process. 
```
hls_model.build(csim=False, synth=True, vsynth=True)
```

```
INFO: [XFORM 203-101] Partitioning array 'shift_buffer.V' (firmware/nnet_utils/nnet_conv_stream.h:217) in dimension 2 completely.
INFO: [XFORM 203-101] Partitioning array 'shift_buffer.V' (firmware/nnet_utils/nnet_conv_stream.h:217) in dimension 2 completely.
INFO: [XFORM 203-101] Partitioning array 'shift_buffer.V' (firmware/nnet_utils/nnet_conv_stream.h:217) in dimension 2 completely.
INFO: [XFORM 203-101] Partitioning array 'shift_buffer.V' (firmware/nnet_utils/nnet_conv_stream.h:217) in dimension 2 completely.
INFO: [XFORM 203-101] Partitioning array 'shift_buffer.V' (firmware/nnet_utils/nnet_conv_stream.h:217) in dimension 2 completely.

/tools/Xilinx/Vivado/2018.2/bin/rdiArgs.sh: line 194:  8288 Killed                  "$RDI_PROG" "$@"
Synthesis report not found.
```

**Comment by jmduarte** [comment]
The `Killed` line seems to mean that the Linux kernel killed the process for taking too much memory (out of memory killer). Do you know how much RAM this machine has? Typically you need quite a lot to run synthesis/build firmware with Vivado.

Although this page (https://www.xilinx.com/products/design-tools/vivado/vivado-ml.html#documentation) seems to indicate you only need 2 GB of RAM for the Pynq-Z2 (XC7Z020), it may depends on the number of cores you're using. I would definitely also use a machine with much more RAM (like 32 GB)

**Comment by jmduarte** [comment]
Also, the latest hls4ml tutorial has been updated to include these exercises with a more recent release of hls4ml: https://github.com/fastmachinelearning/hls4ml-tutorial/blob/master/part7_deployment.ipynb

**Comment by wilfredkisku** [comment]
Thank you for the reply. Actually, I have modified the code so that I can synthesize it for the ZCU104, there are architectural changes to the model and I am using 2D convolutions and images as the input. 

As you mentioned that it might be a memory issue, I do suspect that. I am running the synthesis on a Ubuntu VM that has a memory of 16 GB. Any suggestions on the number of parameters (in terms of filters that hls4ml can handle)?

Thank you very much for your reply.

**Comment by wilfredkisku** [comment]
> Also, the latest hls4ml tutorial has been updated to include these exercises with a more recent release of hls4ml: https://github.com/fastmachinelearning/hls4ml-tutorial/blob/master/part7_deployment.ipynb

I am following the current tutorial but they all fail (part6_cnns.ipynb), while I do a logic sysnthesis (build).

**Comment by jmduarte** [comment]
ok, let's follow up there or on your hls4ml issue instead then?
