### ISSUE TITLE
Pynq backend issue

### ISSUE THREAD

**Issue by pipawoz** [jmduarte/pynq_hls4ml#3]
Hi. Apparently the hls4ml.converter has an issue with the backend argument in the file [pynq_test.py](https://github.com/jmduarte/pynq_hls4ml/blob/main/pynq_test.py)

```python
hls_model = hls4ml.converters.convert_from_keras_model(model,
                                                       hls_config=config,
                                                       output_dir='model_1/hls4ml_prj',
                                                       fpga_part='xc7z020clg400-1',
                                                       backend='Pynq')


Traceback (most recent call last):
  File "test_pynq.py", line 84, in <module>
    hls_model = hls4ml.converters.convert_from_keras_model(model,
TypeError: convert_from_keras_model() got an unexpected keyword argument 'backend'
```

```bash
pip3 install git+git://github.com/jmduarte/hls4ml.git@pynq#egg=hls4ml[profiling]
zsh: no matches found: git+git://github.com/jmduarte/hls4ml.git@pynq#egg=hls4ml[profiling]
```

Is possible that the example is outdated according to the main repo of hls4ml?  Is there a change on the functionality if not using the "backend" argument but using the "fgpa_part"?

**Comment by jmduarte** [comment]
Hi @pipawoz,

As shown here: https://github.com/jmduarte/pynq_hls4ml/blob/main/environment.yml#L15

This example is currently written to work with this branch: https://github.com/jmduarte/hls4ml/tree/pynq

Could you try installing like this instead:
```
pip install git+https://github.com/jmduarte/hls4ml.git@pynq#egg=hls4ml[profiling]
```

There is an open pull request to bring these changes into the hls4ml main branch: https://github.com/fastmachinelearning/hls4ml/pull/349

but as you say, there are some minor API changes to make it work with that once merged (`Pynq` -> `VivadoAccelerator` and small changes like this).
